<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <BepInExPluginGuid>p1xel8ted.sunhaven.cheatenabler</BepInExPluginGuid>
        <AssemblyVersion>$(Version)</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>
        <NexusGroupId>123220</NexusGroupId>
    </PropertyGroup>

    <Import Project="..\zip.target"/>


</Project>
