<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <BepInExPluginGuid>p1xel8ted.sunhaven.morethemerrier</BepInExPluginGuid>
        <AssemblyVersion>$(Version)</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <Import Project="..\zip.target"/>


</Project>
