<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <BepInExPluginGuid>p1xel8ted.sunhaven.autotools</BepInExPluginGuid>
        <AssemblyVersion>$(Version)</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>
        <NexusGroupId>819364</NexusGroupId>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DefineConstants>TRACE;AT</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DefineConstants>TRACE;AT</DefineConstants>
    </PropertyGroup>

    <Import Project="..\zip.target"/>

</Project>
